_target_: pytorch_lightning.Trainer

gpus: 0

min_epochs: 1
max_epochs: 20 # recipe 200

# number of validation steps to execute at the beginning of the training
# num_sanity_val_steps: 0
num_sanity_val_steps: 0
log_every_n_steps: 10
check_val_every_n_epoch: 1
gradient_clip_val: 0.1 #frec
#gradient_clip_val: 4.0  #recippe 1.0
#val_check_interval: 1.0
